### ISSUE TITLE
Disable lines number

### ISSUE THREAD

**Issue by PH7-Jack** [torchlight-api/torchlight-laravel#19]
I would like to know if it is possible to disable the lines in a specific example

**Comment by aarondfrancis** [comment]
Yup! You can turn them off per block by passing `{"lineNumbers": false}` as an option.

See https://torchlight.dev/docs/options/line-numbers and https://torchlight.dev/docs/options#setting-options-per-block

**Comment by PH7-Jack** [comment]
Amazing. Thanks
