### ISSUE TITLE
Looks like `<!-- Comments --> in PHP/HTML files do not work

### ISSUE THREAD

**Issue by ralphjsmit** [torchlight-api/torchlight-laravel#34]
Hey Aaron! I've been converting my blog from WordPress to Laravel. With that I'm also switching to Torchlight.

One thing that struck me was the following code snippet:

<img width="633" alt="Schermafbeelding 2022-03-10 om 18 03 51" src="https://user-images.githubusercontent.com/59207045/157716361-c2d30d4e-2489-44ca-863a-29f11b22aaa1.png">

This is a code snippet in a PHP that is rendered as HTML. In this case, the first line is just an HTML-comment, but it isn't grey like it should be.

Is this indeed a bug or should I use a different filetype than `PHP`? 

Thanks!

**Comment by aarondfrancis** [comment]
Hmm that does indeed seem wrong, let me look into that really quick

**Comment by aarondfrancis** [comment]
Ok for files like that give `php-html` a try. I need to document that because it confused me too 😂

**Comment by aarondfrancis** [comment]
I'm working on a better solution to this.

**Comment by ralphjsmit** [comment]
Thank you for researching this! It works better, though it looks like the HTML-part isn't fully rendered. Do you also have that?

<img width="690" alt="Schermafbeelding 2022-03-11 om 08 35 13" src="https://user-images.githubusercontent.com/59207045/157822941-bf1cf16b-5076-4c3e-ae3e-8c0c14baf009.png">

**Comment by ralphjsmit** [comment]
No problem, nothing urgent👍

**Comment by aarondfrancis** [comment]
Fixed! You can use `php` and if it notices opening tags `<?php` it will default under-the-hood to `php-html` and actually highlight the HTML properly now

**Comment by ralphjsmit** [comment]
Great, thank you Aaron! You absolutely did a great job with Torchlight. Initially I was somewhat skeptical of doing an API-call for highlighting, but with the caching in Laravel it's very fast and beautiful.
