### ISSUE TITLE
Not installing in Laravel 11

### ISSUE THREAD

**Issue by CodingwithRK** [torchlight-api/torchlight-laravel#56]
Hi I am trying to install in Laravel 11 project.

`composer require torchlight/torchlight-laravel
./composer.json has been updated
Running composer update torchlight/torchlight-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - torchlight/torchlight-laravel[v0.1.0, ..., v0.5.10] require illuminate/support ^7.26.0|^8.0 -> found illuminate/support[v7.26.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - torchlight/torchlight-laravel[v0.5.11, ..., v0.5.12] require illuminate/support ^7.26.0|^8.0|^9.0 -> found illuminate/support[v7.26.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - torchlight/torchlight-laravel v0.5.13 requires illuminate/support ^7.26.0|^8.0|^9.0|^10.0 -> found illuminate/support[v7.26.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.10] but these were not loaded, likely because it conflicts with another require.
    - torchlight/torchlight-laravel v0.5.14 requires illuminate/support ^8.0|^9.0|^10.0 -> found illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.10] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires torchlight/torchlight-laravel * -> satisfiable by torchlight/torchlight-laravel[v0.1.0, ..., v0.5.14].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require torchlight/torchlight-laravel:*" to figure out if any version is installable, or "composer require torchlight/torchlight-laravel:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

I am getting this error.

Please anyone can help me to figure it out.

Thank you. ☺️

**Comment by robdekort** [comment]
Oh yeah, plus one for this. I bet the composer file needs an update and this project needs a new release. Awaiting this as well for a customer who subscribed for the business license. Hoping for an update soon.

**Comment by Muetze42** [comment]
The merge request has been open since February:
https://github.com/torchlight-api/torchlight-laravel/pull/54

Try to install this branch:
https://github.com/laravel-shift/torchlight-laravel/tree/l11-compatibility

Instructions:
https://github.com/torchlight-api/torchlight-laravel/pull/54#issuecomment-1967289348

**Comment by CodingwithRK** [comment]
Thank you @Muetze42 , now working
